# Docs: https://docs.codecov.io/docs/codecov-yaml
# NB: Product (app) name and target name must match

ignore:
  - docs/.*
  - fastlane/.*
  - Poses/resources/.*
  - Poses/sdks/.*
  - PosesTests/.*
  - PosesUITests/.*
  - Pods/.*
