// @copyright Trollwerks Inc.

@testable import Poses

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class ReportingServiceSpy: ReportingService {
    var invokedEvent = false
    var invokedEventCount = 0
    var invokedEventParameters: (event: AnalyticsEvent, Void)?
    var invokedEventParametersList = [(event: AnalyticsEvent, Void)]()
    func event(_ event: AnalyticsEvent) {
        invokedEvent = true
        invokedEventCount += 1
        invokedEventParameters = (event, ())
        invokedEventParametersList.append((event, ()))
    }
    var invokedStart = false
    var invokedStartCount = 0
    var invokedStartParameters: (event: AnalyticsEvent, Void)?
    var invokedStartParametersList = [(event: AnalyticsEvent, Void)]()
    func start(_ event: AnalyticsEvent) {
        invokedStart = true
        invokedStartCount += 1
        invokedStartParameters = (event, ())
        invokedStartParametersList.append((event, ()))
    }
    var invokedFinish = false
    var invokedFinishCount = 0
    var invokedFinishParameters: (event: AnalyticsEvent, Void)?
    var invokedFinishParametersList = [(event: AnalyticsEvent, Void)]()
    func finish(_ event: AnalyticsEvent) {
        invokedFinish = true
        invokedFinishCount += 1
        invokedFinishParameters = (event, ())
        invokedFinishParametersList.append((event, ()))
    }
    var invokedScreen = false
    var invokedScreenCount = 0
    var invokedScreenParameters: (name: String, Void)?
    var invokedScreenParametersList = [(name: String, Void)]()
    func screen(_ name: String) {
        invokedScreen = true
        invokedScreenCount += 1
        invokedScreenParameters = (name, ())
        invokedScreenParametersList.append((name, ()))
    }
    var invokedBreadcrumb = false
    var invokedBreadcrumbCount = 0
    var invokedBreadcrumbParameters: (breadcrumb: String, Void)?
    var invokedBreadcrumbParametersList = [(breadcrumb: String, Void)]()
    func breadcrumb(_ breadcrumb: String) {
        invokedBreadcrumb = true
        invokedBreadcrumbCount += 1
        invokedBreadcrumbParameters = (breadcrumb, ())
        invokedBreadcrumbParametersList.append((breadcrumb, ()))
    }
    var invokedError = false
    var invokedErrorCount = 0
    var invokedErrorParameters: (error: Error, id: String, message: String, params: [AnyHashable: Any])?
    var invokedErrorParametersList = [(error: Error, id: String, message: String, params: [AnyHashable: Any])]()
    func error(_ error: Error,
    id: String,
    message: String,
    params: [AnyHashable: Any]) {
        invokedError = true
        invokedErrorCount += 1
        invokedErrorParameters = (error, id, message, params)
        invokedErrorParametersList.append((error, id, message, params))
    }
}
